GoogleCloudDataproc/flink-bigquery-connector

src/main/java/com/google/cloud/flink/bigquery/ArrowDeserializationSchema.java, src/main/java/com/google/cloud/flink/bigquery/ArrowFormatFactory.java, src/main/java/com/google/cloud/flink/bigquery/ArrowRowDataDeserializationSchema.java, src/main/java/com/google/cloud/flink/bigquery/BigQueryArrowFormat.java, src/main/java/com/google/cloud/flink/bigquery/BigQueryDynamicTableFactory.java, src/main/java/com/google/cloud/flink/bigquery/arrow/util/ArrowToRowDataConverters.java
Read part -> record type changes
=> big query record type changes

CHANGES.md
Required for release automation
/gcbrun
=> Add a changes md file

cloudbuild/nightly/scripts/python-scripts/create_cluster.py, flink-1.17-connector-bigquery/flink-connector-bigquery-integration-test/src/main/java/com/google/cloud/flink/bigquery/integration/BigQueryIntegrationTest.java
=> Modifies documentation for Integration Test file

pom.xml
Inferred from spark bq connector: https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/master/spark-bigquery-parent/pom.xml#L39
=> Add distribution management in pom for nexus

README.md, flink-1.17-connector-bigquery/flink-connector-bigquery-examples/pom.xml, flink-1.17-connector-bigquery/flink-connector-bigquery-integration-test/pom.xml, flink-1.17-connector-bigquery/flink-connector-bigquery/pom.xml, flink-1.17-connector-bigquery/pom.xml, flink-connector-bigquery-common/pom.xml, pom.xml
DO_NOT_MERGE!
- change documented version to 0.2.0 for next release
- add url, license, developer info and scm in pom
- change project version to snaphot
=> Prepare for release to maven

CHANGES.md
Complete automated 0.2.0 release
=> Release 0.2.0

flink-1.17-connector-bigquery/flink-connector-bigquery/src/main/java/com/google/cloud/flink/bigquery/sink/serializer/AvroToProtoSerializer.java
Replaces the existing implementation with an if-else based to increase performance. 
@talatuyarer - Please have a look.
/gcbrun
=> Optimization for handleUnionSchema.

flink-1.17-connector-bigquery/flink-connector-bigquery/src/test/java/com/google/cloud/flink/bigquery/fakes/StorageClientFaker.java
=> Modify storage client faker to create different instances

CHANGES.md
=> Update changes md for next release

flink-connector-bigquery-common/src/main/java/com/google/cloud/flink/bigquery/services/BigQueryServicesImpl.java, flink-connector-bigquery-common/src/main/java/com/google/cloud/flink/bigquery/source/split/SplitDiscoverer.java
Populate User Agent Header and Trace ID.
/gcbrun
=> Track Read and Write API usage

CHANGES.md, README.md, flink-1.17-connector-bigquery/flink-connector-bigquery-examples/src/main/java/com/google/cloud/flink/bigquery/examples/BigQueryExample.java, flink-1.17-connector-bigquery/flink-connector-bigquery-table-api-examples/src/main/java/com/google/cloud/flink/bigquery/examples/BigQueryTableExample.java
Also, re-ordered sink and source descriptions in readme. The packaging of unshaded guava is a ToDo.
/gcbrun
=> Update examples, readme and changes md

README.md
=> Elaborate on restart strategy enforcement

CHANGES.md
Reverts #175. Desired change was implemented in #177.
/gcbrun
=> Revert "Update CHANGES.md"

flink-1.17-connector-bigquery/flink-connector-bigquery-integration-test/src/main/java/com/google/cloud/flink/bigquery/integration/BigQueryIntegrationTest.java
=> Fix restart strategy in e2e test

flink-1.17-connector-bigquery/flink-connector-bigquery/src/test/java/com/google/cloud/flink/bigquery/fakes/StorageClientFaker.java, flink-connector-bigquery-common/src/main/java/com/google/cloud/flink/bigquery/common/utils/BigQueryTableInfo.java, flink-connector-bigquery-common/src/main/java/com/google/cloud/flink/bigquery/services/BigQueryServices.java, flink-connector-bigquery-common/src/main/java/com/google/cloud/flink/bigquery/services/BigQueryServicesImpl.java
Utilities to be used when implementing table auto creation
/gcbrun
=> Add methods to check exists and create BQ dataset

flink-1.17-connector-bigquery/flink-connector-bigquery/src/main/java/com/google/cloud/flink/bigquery/sink/writer/CreateTableOptions.java
=> Fix config

flink-1.17-connector-bigquery/flink-connector-bigquery/src/main/java/com/google/cloud/flink/bigquery/sink/BigQueryBaseSink.java, flink-1.17-connector-bigquery/flink-connector-bigquery/src/main/java/com/google/cloud/flink/bigquery/sink/BigQueryDefaultSink.java, flink-1.17-connector-bigquery/flink-connector-bigquery/src/main/java/com/google/cloud/flink/bigquery/sink/BigQueryExactlyOnceSink.java, flink-1.17-connector-bigquery/flink-connector-bigquery/src/main/java/com/google/cloud/flink/bigquery/sink/writer/BaseWriter.java, flink-1.17-connector-bigquery/flink-connector-bigquery/src/main/java/com/google/cloud/flink/bigquery/sink/writer/BigQueryBufferedWriter.java, flink-1.17-connector-bigquery/flink-connector-bigquery/src/main/java/com/google/cloud/flink/bigquery/sink/writer/BigQueryDefaultWriter.java, flink-1.17-connector-bigquery/flink-connector-bigquery/src/test/java/com/google/cloud/flink/bigquery/fakes/StorageClientFaker.java, flink-1.17-connector-bigquery/flink-connector-bigquery/src/test/java/com/google/cloud/flink/bigquery/sink/writer/BigQueryBufferedWriterTest.java, flink-1.17-connector-bigquery/flink-connector-bigquery/src/test/java/com/google/cloud/flink/bigquery/sink/writer/BigQueryDefaultWriterTest.java, flink-connector-bigquery-common/src/main/java/com/google/cloud/flink/bigquery/services/BigQueryServices.java, flink-connector-bigquery-common/src/main/java/com/google/cloud/flink/bigquery/services/BigQueryServicesImpl.java
=> Add UUID to traceId in sink

flink-1.17-connector-bigquery/flink-connector-bigquery/src/main/java/com/google/cloud/flink/bigquery/source/BigQuerySource.java, pom.xml
Change suggested by @ryanvanhuuksloot: https://github.com/GoogleCloudDataproc/flink-bigquery-connector/pull/200
/gcbrun
=> Use avro name sanitization in source

README.md, flink-1.17-connector-bigquery/flink-connector-bigquery/src/main/java/com/google/cloud/flink/bigquery/sink/serializer/AvroToProtoSerializer.java
- fix read.limit documentation to clarify that it operates per task slot
- propagate errors from avro serializer
- mention incompatible data types in documentation
/gcbrun
=> Address user feedback

CHANGES.md, README.md
=> Prepare docs for next release
